[renderer]
samples = 100
depth-limit = 100
integrator = "wireframe"
show = false

[sampler]
type = "minstd"

[film]
resolution = [512, 512]

[sky]
type = "uniform"
color = [1, 1, 1]

[camera]
type = "ideal-pinhole"
fov = 60.0
lens-distance = 1.2
focus-point = [0.0, 1.0, 0.0]
f-number = 14.0
[camera.transform]
type = "look-at"
origin = [0, 1, 3]
target = [0, 1, 0]

[[material]]
name = "mat1"
type = "lambert"
albedo = [0.9, 0.9, 0.9]

[[mesh]]
name = "cbox"
type = "obj"
path = "CornellBox-Original.obj"


[[object]]
name = "cbox"
mesh = "cbox"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]
