[renderer]
samples = 30
depth-limit = 100
integrator = "pt-explicit"
show = true

[sampler]
type = "minstd"

[film]
resolution = [1024, 1024]

[sky]
type = "uniform"
color = [0, 0, 0]
path = "Mans_Outside_2k.hdr"
theta-offset = 0
phi-offset = 3.14

[camera]
type = "full-degree"
fov = 60.0
lens-distance = 1.2
focus-point = [0.0, 1.0, 0.0]
f-number = 14.0
[camera.transform]
type = "look-at"
origin = [278.1, 273, 100]
target = [278, 273, 101]

[[material]]
name = "mat1"
type = "lambert"
albedo = [0.9, 0.9, 0.9]

[[mesh]]
name = "cbox"
type = "obj"
path = "cbox.obj"
[[mesh]]
name = "light"
type = "obj"
path = "cbox_luminaire.obj"
[[mesh]]
name = "dragon"
type = "obj"
path = "dragon.obj"


[[object]]
name = "cbox"
mesh = "cbox"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]

[[object]]
name = "light"
mesh = "light"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]

[[object]]
name = "dragon"
mesh = "dragon"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [278, 0, 300]
[[object.transform]]
type = "scale"
vector = [30.0, 30.0, 30.0]


[[light]]
type = "area"
object = "light"
emission = [40, 30, 22]
