[renderer]
samples = 100
depth-limit = 100
integrator = "pt-explicit"
show = false

[sampler]
type = "mt"

[film]
resolution = [256, 256]

[sky]
type = "uniform"
color = [0, 0, 0]

[camera]
type = "ideal-pinhole"
ipd = 1.0
fov = 90.0
[camera.transform]
type = "look-at"
origin = [278, 273, -100]
target = [278, 273, 100]

[[material]]
name = "blue"
type = "lambert"
albedo = [0.2, 0.2, 0.8]
[[material]]
name = "white"
type = "lambert"
albedo = [0.9, 0.9, 0.9]

[[mesh]]
name = "cbox"
type = "obj"
path = "cbox.obj"
[[mesh]]
name = "light"
type = "obj"
path = "cbox_luminaire.obj"
[[mesh]]
name = "sphere"
type = "sphere"
radius = 80.0
[[mesh]]
name = "sphere2"
type = "sphere"
radius = 100.0

[[object]]
name = "cbox"
mesh = "cbox"
material = "white"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]

[[object]]
name = "light"
mesh = "light"
material = "white"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 0.0]

[[object]]
name = "sphere"
mesh = "sphere"
material = "blue"
[[object.transform]]
type = "translate"
vector = [390, 150, 350]

[[object]]
name = "sphere2"
mesh = "sphere2"
material = "white"
[[object.transform]]
type = "translate"
vector = [200, 150, 270]

[[light]]
type = "area"
object = "light"
emission = [40, 30, 22]
