[renderer]
samples = 10
depth-limit = 100
integrator = "pt-explicit"
show = true
profile = false

[sampler]
type = "mt"

[film]
resolution = [512, 512]

[sky]
type = "uniform"
color = [0, 0, 0]
path = "Mans_Outside_2k.hdr"
theta-offset = 0
phi-offset = 3.14

[camera]
type = "ideal-pinhole"
ipd = 0.1
fov = 90.0
lens-distance = 1.0 
focus-point = [0.0, 1.0, 0.0]
f-number = 8.0 
[camera.transform]
type = "look-at"
origin = [0.0, 1.0, -3.0]
target = [0.0, 0.5, 0.0]

[[material]]
name = "mat1"
type = "phong"
kd = 0.9
albedo = [1.0, 1.0, 1.0]
alpha = 1.0
[[material]]
name = "mat2"
type = "phong"
kd = 1.0 
albedo = [1.0, 1.0, 1.0]
alpha = 1.0
[[material]]
name = "mat3"
type = "phong"
kd = 1.0 
albedo = [1.0, 1.0, 1.0]
alpha = 1.0
[[material]]
name = "mat4"
type = "phong"
kd = 0.9
albedo = [1.0, 1.0, 1.0]
alpha = 1.0
[[material]]
name = "mat5"
type = "phong"
kd = 0.9
albedo = [1.0, 1.0, 1.0]
alpha = 1.0


[[mesh]]
name = "floor"
type = "obj"
path = "plane.obj"

[[mesh]]
name = "sphere1"
type = "sphere"
radius = 0.1
[[mesh]]
name = "sphere2"
type = "sphere"
radius = 0.2
[[mesh]]
name = "sphere3"
type = "sphere"
radius = 0.4
[[mesh]]
name = "sphere4"
type = "sphere"
radius = 0.8


[[object]]
name = "plate1"
mesh = "floor"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [0, 0, 0]
[[object.transform]]
type = "scale"
vector = [1.0, 1.0, 0.3]
[[object]]
name = "plate2"
mesh = "floor"
material = "mat2"
[[object.transform]]
type = "translate"
vector = [0, 0, 3]
[[object.transform]]
type = "scale"
vector = [1.0, 1.0, 0.3]
[[object]]
name = "plate3"
mesh = "floor"
material = "mat3"
[[object.transform]]
type = "translate"
vector = [0, 0, 6]
[[object.transform]]
type = "scale"
vector = [1.0, 1.0, 0.3]

[[object]]
name = "light1"
mesh = "sphere1"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [3.0, 10.0, 10.0]
[[object]]
name = "light2"
mesh = "sphere2"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [0.0, 10.0, 10.0]
[[object]]
name = "light3"
mesh = "sphere3"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [-3.0, 10.0, 10.0]

[[light]]
type = "area"
object = "light1"
emission = [1000.0, 0.0, 300.0]
[[light]]
type = "area"
object = "light2"
emission = [1000.0, 300.0, 0.0]
[[light]]
type = "area"
object = "light3"
emission = [0.0, 300.0, 1000.0]

