[renderer]
samples = 100
depth-limit = 100
integrator = "pt"
show = false

[sampler]
type = "mt"

[film]
resolution = [4000, 4000]

[sky]
type = "ibl"
path = "PaperMill_E_3k.hdr"
theta-offset = 0
phi-offset = 2.0

[camera]
type = "full-degree"
fov = 40.0
lens-distance = 1.5
focus-point = [0.0, 1.6329, 1.1547]
f-number = 8.0
[camera.transform]
type = "look-at"
origin = [3.0, 4.0, -4.5]
target = [0.0, 1.6329, 1.1547]
[[material]]
name = "mat1"
type = "lambert"
albedo = [0.2, 0.5, 0.9]

[[material]]
name = "mat2"
type = "mirror"
albedo = 0.9

[[material]]
name = "mat3"
type = "phong"
kd = 0.9
albedo = [1.0, 1.0, 1.0]
alpha = 500.0 

[[material]]
name = "glass"
type = "glass"
ior = 1.5

[[material]]
name = "diamond"
type = "glass"
ior = 2.4195

[[mesh]]
name = "floor"
type = "obj"
path = "plane.obj"

[[mesh]]
name = "dragon"
type = "obj"
path = "dragon.obj"

[[mesh]]
name = "teapot"
type = "obj"
path = "teapot.obj"

[[mesh]]
name = "bunny"
type = "obj"
path = "bunny.obj"

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0

[[mesh]]
name = "diamond"
type = "obj"
path = "diamond.obj"


[[object]]
name = "floor"
mesh = "floor"
material = "mat1"
[[object.transform]]
type = "translate"
vector = [0.0, 0.0, 1.1547]
[[object.transform]]
type = "scale"
vector = [1.5, 1.5, 1.5]

[[object]]
name = "sphere"
mesh = "sphere"
material = "glass"
[[object.transform]]
type = "translate"
vector = [0.0, 1.0, 0.0]

[[object]]
name = "sphere2"
mesh = "sphere"
material = "glass"
[[object.transform]]
type = "translate"
vector = [1.0, 1.0, 1.7320]

[[object]]
name = "sphere3"
mesh = "sphere"
material = "glass"
[[object.transform]]
type = "translate"
vector = [-1.0, 1.0, 1.7320]

[[object]]
name = "sphere4"
mesh = "sphere"
material = "glass"
[[object.transform]]
type = "translate"
vector = [0.0, 2.6329, 1.1547]
