[renderer]
samples = 1000
depth-limit = 100
integrator = "pt"

[film]
resolution = [512, 512]

[sky]
type = "ibl"
path = "PaperMill_E_3k.hdr"
theta-offset = 0
phi-offset = 3.14

[camera]
type = "ideal-pinhole"
fov = 60.0
lens-distance = 1.5
focus-point = [0, 1, 0]
f-number = 8.0 
[camera.transform]
type = "look-at"
origin = [0, 2, -5]
target = [0, 1, 0]

[[material]]
name = "mat1"
type = "lambert"
albedo = [0.9, 0.9, 0.9]

[[material]]
name = "mat2"
type = "mirror"
albedo = 0.9

[[material]]
name = "mat3"
type = "phong"
alpha = 5000.0

[[material]]
name = "mat4"
type = "glass"
ior = 1.4

[[mesh]]
name = "floor"
type = "obj"
path = "plane.obj"

[[mesh]]
name = "dragon"
type = "obj"
path = "dragon.obj"

[[mesh]]
name = "teapot"
type = "obj"
path = "teapot.obj"

[[mesh]]
name = "sphere"
type = "sphere"
radius = 1.0

[[object]]
mesh = "floor"
material = "mat3"
[[object.transform]]
type = "translate"
vector = [0, 0, 0]

[[object]]
mesh = "sphere"
material = "mat4"
[[object.transform]]
type = "translate"
vector = [0, 1, 0]
